name: quantum-ml
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost
  - lightgbm
  - optuna
  - shap
  - lime
  - plotly
  - jupyterlab
  - notebook
  - missingno

  - pip:
      - qiskit
      - ipywidgets
      - tqdm
      - kaleido
  
