name: Quantum ML CI/CD Pipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  check-merge-conflicts:
    name: Check Merge Conflicts
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base
          fetch-depth: 0

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: pr
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Check for merge conflicts
        run: |
          cd base
          git remote add pr ../pr
          git fetch pr
          git merge FETCH_HEAD --no-commit --no-ff || (echo "❌ Merge conflict detected!" && exit 1)



  build-and-test:
    name: Build & Test Notebooks
    runs-on: ubuntu-latest
    needs: check-merge-conflicts
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: quantum-ml
          python-version: "3.10"

      - name: Install extras
        run: |
          conda run -n quantum-ml
          pip install papermill nbconvert

      - name: Run notebooks with papermill
        run: |
          if ls notebooks/*.ipynb 1> /dev/null 2>&1; then
            mkdir -p artifacts
            for nb in notebooks/*.ipynb; do
              conda run -n quantum-ml papermill "$nb" "artifacts/$(basename "$nb")"
            done
          else
            echo "⚠️ No notebooks found in the notebooks/ directory."
          fi

      - name: Convert notebooks to HTML
        run: |
          mkdir -p artifacts_html
          if compgen -G "artifacts/*.ipynb" > /dev/null; then
            echo "✅ Notebooks found. Converting to HTML..."
            conda run -n quantum-ml jupyter nbconvert --to html artifacts/*.ipynb --output-dir artifacts_html
          else
            echo "⚠️ No notebooks found in artifacts/. Skipping conversion."
          fi

      - name: Upload HTML Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-reports
          path: artifacts_html/

  deploy:
    name: Deploy to GitHub Pages
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: html-reports
          path: public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

